### ISSUE TITLE
Add Streaming Support

### ISSUE THREAD

**Issue by jhabdas** [brentsimmons/JSONFeed#105]
Consider the following quote from [jsonfeed.org](https://jsonfeed.org):

> JSON is simpler to read and write, and it’s less prone to bugs.

What is the justification behind <q>less prone to bugs</q>? What does that even mean? As I understand it (based on years of use) JSON is one of the most persnickety formats available. A single little misplaced comma and BOOM you've got invalid JSON. You should remove that quote unless you can back it up with data. Otherwise I'm afraid it's extremely misleading.

Which brings me to streaming. If JSON feeds are to go anywhere with the persnickety syntax JSON requires, I'm interested in hearing thoughts on *only* allowing JSON feeds to work by way of streaming. That is to say, a stream is established and everything comes down in little pieces. Each item in the stream is another small piece of JSON.

Without streaming support I don't see how JSON Feeds could ever actually be realized. In fact, I could see TOML making it further.

**Comment by jhabdas** [comment]
This might help solve the problem of embedding markup in JSON. Though it's very much in draft AFACT: http://json-schema.org/latest/json-schema-hypermedia.html.

Casual observation tells me this is less becomes much less light and readable when compared with XML. YMMV.

**Comment by jhabdas** [comment]
https://github.com/toml-lang/toml/issues/465 Looks like TOML may be getting a registered MIME type soon. Eyes on the IANA registry.

**Comment by fboes** [comment]
For streaming there ist also a JSONesque alternative called `ndjson`. Check out http://ndjson.org/

JSON-Feed in `ndjson` could look like this:

```
{"version": "https://jsonfeed.org/version/1","title": "My Example Feed","home_page_url": "https://example.org/","feed_url": "https://example.org/feed.json"}
{"id": "2","content_text": "This is a second item.","url": "https://example.org/second-item"}
{"id": "1","content_html": "<p>Hello, world!</p>","url": "https://example.org/initial-post"}
```

But actually it would be quiet possible to read streaming JSON (like it is possible to read streaming XML) - check out https://www.npmjs.com/package/stream-json

"Being less error-prone" may refer to the rather simple implementation of JSON gerenators, e.g. in PHP's `json_encode()` and Javascript's `JSON.stringify()` - and its rather robust parser counterparts like PHP's `json_decode()` and Javascript's `JSON.parse()`.

**Comment by jhabdas** [comment]
JSON is a travesty. But I have hope for us.

**Comment by BenLeggiero** [comment]
This is an issue for parsers, not for the spec.

**Comment by jhabdas** [comment]
Here's a thought on providing streaming support: http://jsonlines.org/. Note I'm still personally opposed to JSON feed as JSON itself is flimsy and RSS and Atom are de facto standards we should put more energy behind before inventing something shiny and new.

**Comment by BenLeggiero** [comment]
@jhabdas Perhaps you want paging support? Where you tell the server "give me a page where there are `n` entries before it, and the page contains at most `m` entries"? This is distinct from streaming support in that you never have to worry about a partial file.

On the note about misplaced commas, that should never be a concern. Automated feed generators won't do that, and someone with the guts to make a feed manually will (first off be very rare, if nonexistent, but secondly) know what they're doing, and probably use an editor which will throw up errors if they write invalid JSON.

When it comes to making the parser supporting reading up to any arbitrary point in a JSON file without modifying the spec at all (for instance, if its bytes are still streaming in and you want to read it impatiently), simply have it close all still-open quotes, brackets, braces, etc., remove any dangling comma, and you now have a valid truncated JSON string. I wouldn't write a parser to do this, but it wouldn't be hard. Heck, you could probably do it with regexes.

**Do you have real-world examples of where streaming, not paging, support in a feed spec has been crucial to its usage?**

**Comment by jhabdas** [comment]
@BenLeggiero really looking for streaming. cant remember where I saw it but there's something out there which allows it for JSON. this issue isn't going anywhere so please feel free to bring forward into a new issue.
