### ISSUE TITLE
Require RFC 3339 datetimes

### ISSUE THREAD

**Issue by foresmac** [brentsimmons/JSONFeed#11]
ISO 8601 actually allows a pretty wide variety of formats. [RFC 3339](https://www.ietf.org/rfc/rfc3339.txt) offers a more specific ISO 8601 profile that's easier to parse correctly. (If I had my way, I'd require all timestamps to be UTC, as well.)

**Comment by fazalmajid** [comment]
I'd recommend using UNIX timestamps (which are intrinsically UTC, leap seconds and all),  expressed as integers and getting rid of all the date parsing issues and overhead.

My credentials: I wrote the first complete ISO 8601 implementation for Mark Pilgrim's universal feed parser in 2004, and I am the author of the Temboz feed reader, which has truckloads of normalization code: https://github.com/fazalmajid/temboz

**Comment by tomhamming** [comment]
If straight UNIX timestamps are / were explicitly rejected, I'm curious to hear the rationale. They seem way easier to parse - ISO 8601 isn't built into iOS or Android and [isn't obvious](http://stackoverflow.com/questions/3556144/how-to-create-a-net-datetime-from-iso-8601-format) in .NET - and they save a few bytes in transit.

**Comment by kr** [comment]
Decoding an integer unix timestamp is easier than parsing RFC 3339 in most systems, but it's not a slam dunk IMO. One benefit of RFC 3339 times is that one doesn't necessarily have to parse them at all. Some user agent software can simply display the string as-is.

(If saving "a few bytes in transit" were very important here, I doubt this file format would be using JSON in the first place. Also, gzip is a thing.)

**Comment by foresmac** [comment]
@fazalmajid I'd agree with you if the format were only meant to be machine readable, but if I understand correctly, the intent is that JSONFeed is also human readable (or at least, certainly more so than XML).

@tomhamming We always use RFC 3339 in Zulu/UTC for our APIs because at the least you can use a single parsing format for strptime. Also, it's literally the "Internet Time Standard".

**Comment by manton** [comment]
Thanks for the discussion, everyone! The date has to be readable by a human, since one of the goals for JSON Feed is for the format to be as clean and obvious as possible. I think y'all are right about RFC 3339, though. That date format was really the intent.

**Comment by foresmac** [comment]
@manton It looks like all your examples are RFC 3339, so I'd just explicitly state it to prevent potential parsing errors down the line. I'd go one step further, though, and advocate for UTC only. It reduces parsing overhead even more (skipping the offset), and every platform can automatically convert UTC datetimes to local device time.

**Comment by manton** [comment]
We've corrected the spec (in GitHub, the site itself will update later) to reference RFC 3339. This was really what was meant instead of ISO 8601. Sorry about the confusion there! (UTC is a separate issue, and I'd lean toward not requiring the spec to take a stand on that. Good points, though.)
