### ISSUE TITLE
Is JSONFeed dying?

### ISSUE THREAD

**Issue by nmdias** [brentsimmons/JSONFeed#111]
I feel like there was a lot of hype, and now there are no updates or announcements of any kind. Just issues stacking up.

I don't mean to be rude. It's an honest question. I think a lot of us had high hopes for JSONFeed. Some feedback would be appreciated, thanks.

**Comment by fboes** [comment]
In my opinion for every API or protocol there is one singular factor which tells you if the API / protocol is dying: If it is not used anymore.

As far as I can see people are still implemeting JSONFeed, and there are tons of sites out there generating JSONFeeds.

Keep in mind that JSONFeed is extensible - so it may not be necessary to work on JSONFeed's spec. Just take a look at the rather static specs of RSS - and still almost any blog or news site has it very own RSS feed.

**Comment by manton** [comment]
Not dying! More people are implementing JSON Feed all the time. But activity has slowed down for the summer. I think it was good to let the spec stand as-is for a little while before making changes. It's on my to-do list to review more of these issues on GitHub and restart some discussions.

**Comment by danyao** [comment]
Bump on this question. I only discovered JSON feed recently and it seems a nice idea. It's almost a year since last update on this bug, and not much is happening on the blog. Are you folks still actively working on this? :)

**Comment by manton** [comment]
In an effort to close out some older issues, I'm going to close this one too. 🙂 Thanks!
