### ISSUE TITLE
RESTful JSON

### ISSUE THREAD

**Issue by smizell** [brentsimmons/JSONFeed#114]
We recently worked on capturing a design pattern we called [RESTful JSON](http://restfuljson.org/). It looks like JSONFeed actually uses this pattern. Any interest in adding a note about how this spec uses RESTful JSON?

You can also read more [on Medium](https://medium.com/@Stephen_Mizell/introducing-restful-json-def4e6e52fa6) about this pattern.

**Comment by manton** [comment]
Since we didn't know about RESTful JSON when working on the spec, I don't think it will really clarify anything to link to it, so I'm going to close this. Thanks for the feedback and for writing it up.
