### ISSUE TITLE
attachments at top level

### ISSUE THREAD

**Issue by nsFrankly** [brentsimmons/JSONFeed#115]
can we have attachments at "top level" or are they restricted to "item" level ?

our top level "parent" can have images along with its "children" (items)

**Comment by bcomnes** [comment]
Attachments are restricted to item level by my reading.

**Comment by manton** [comment]
Attachments are mostly for things like podcasts that are delivered with new posts/episodes. There are a couple of fields that are used in both items and top-level, like `author` or images, but I think they should be limited to avoid confusion. Thanks!
