### ISSUE TITLE
Request: It would be nice to allow a paginated form of access...not just the last 10.

### ISSUE THREAD

**Issue by julestburt** [brentsimmons/JSONFeed#123]
I understand this is relying on the RSS 'feed' which has limits of how many last posts to show - but am wondering if you could provide a parameter like last postDate or last postID, to allow a paginated response from this feed, which could go beyond the 10 RSS feeds...?

**Comment by manton** [comment]
This is handled in the spec with the `next_url` field. Servers generating a JSON Feed can point to the "next 10" items using this field. Thanks!
