### ISSUE TITLE
Can I assume size_in_bytes and duration_in_seconds are not doubles?

### ISSUE THREAD

**Issue by zorn** [brentsimmons/JSONFeed#124]
https://jsonfeed.org/version/1

> size_in_bytes (optional, number) specifies how large the file is.
> duration_in_seconds (optional, number) specifies how long it takes to listen to or watch, when played at normal speed.

There is no concept of a half-byte but there is a half second. Can I assume I'll always see integers?

**Comment by manton** [comment]
I was trying to see if there's any precedent elsewhere for using partial seconds in a similar format… Didn't notice any. The duration is really just for showing the user, so it doesn't have to be more precise than whole seconds. I think it's likely you'll only see integers here (but apps should probably gracefully handle it either way).
