### ISSUE TITLE
"mime_type" should be "media_type"

### ISSUE THREAD

**Issue by kasei** [brentsimmons/JSONFeed#13]
I believe "media_type" (as in RFC6838) would be a more appropriate property name for use with attachments as it is more general than the the email-related "MIME type" name. Assuming most attachments will be referring to HTTP URLs, this naming would also align with the HTTP spec.

**Comment by manton** [comment]
Thanks for the suggestion and pointer to RFC 6838. One of the reasons `mime_type` was picked is because it's self-documenting. If you see `media_type`, it might not be obvious what that means, but everyone understands what a MIME type is. You make a good point about correctness, though.
