### ISSUE TITLE
DurationInSeconds and SizeInBytes are bad names

### ISSUE THREAD

**Issue by st3fan** [brentsimmons/JSONFeed#15]
I think those should simply be `duration` and `size` and have the spec define how those are represented in terms of units. It is extremely uncommon to have descriptive names like this in formats.

**Comment by manton** [comment]
Thanks for the feedback. We debated this back and forth... It might be unusual, but it was important to have a format that was as self-documenting as possible. Basically, impossible to get wrong when creating a feed, and these type of fields can be unclear in other formats.

**Comment by valtlai** [comment]
I agree. Also `mime_type` would be renamed to `type`.
