### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by msimerson** [brentsimmons/JSONFeed#17]
Since I didn't see another place to post feedback, I'm posting it here.

> have noticed that JSON has become the developers’ choice for APIs, and that developers will often go out of their way to avoid XML.

This, this, this, and this, 1000 times. I'm a developer. I've got 17 year old APIs I still support using XML and/or SOAP. In **every** case, high on the TODO list is deprecating the XML support entirely. XML is big, slow, and we have to upgrade the XML libs regularly due to vulnerabilities. I've had to write XML generators, validators, and parsers over the years so I don't fear XML, but fondness is something I've never felt for it.

JSON just works. A line or two of code in every programming language that matters.

**Comment by manton** [comment]
Thanks @msimerson!
