### ISSUE TITLE
Title-only items?

### ISSUE THREAD

**Issue by mattgallagher** [brentsimmons/JSONFeed#18]
I really like the aims of this spec but I wanted to raise an issue/question about "title-only items"...

As I read it at the moment, the mandatory fields for an item are:

* `id`
* `content_text` OR `content_html`

Have you considered replacing that second requirement with:

* `content_text` OR `content_html` OR `title`

The reason for this suggestion is that it would allow lists of links to fall within the spec, without mandating a dummy `content_text=""` field. Examples for this use-case include a minimalist feed for a link aggregation site like Hacker News or Reddit which is just "Link Text" (`title`) and "Link" (`id`).

**Alternately...**

If there is an expectation, in the absence of a `title`, that `content_text` may be contextually the "Link Text", perhaps this should be stated explicitly somewhere in the goals, examples or other discussion to reassure users like myself that it wouldn't be perverting the spec to use `content_text` in this way.

I personally would prefer *not* requiring a content tag since sometimes `title` is a more appropriate description of the semantic meaning than "content" (there are even cases where an item that is purely an `id` might be appropriate). I understand though if you'd rather downplay certain content structures.

**Comment by manton** [comment]
Thanks @mattgallagher! My take on this is that it's more appropriate for those items to just use `content_text`. If you think about link-blogging as just a variation of microblogging, it's more consistent to use `content_text` and `content_html` everywhere.

You're right that explicitly mentioning this in the spec is a good idea.

**Comment by valtlai** [comment]
Related: #27
