### ISSUE TITLE
MIME-type should be more specific

### ISSUE THREAD

**Issue by tommy-carlier** [brentsimmons/JSONFeed#22]
The MIME-type of JSONFeed is currently `application/json`. I believe it should be a bit more specific, like `application/feed+json`. RSS and Atom feeds also use `application/rss+xml` and `application/atom+xml`.

If you declare `<link rel=alternate type="application/json" href="/feed.json">` in your HTML-page, you're telling the user agents that feed.json is just a JSON-representation of the current document, not necessarily a feed. If you use `application/feed+json`, you're telling them specifically that it's a feed that can be subscribed to.

**Comment by mstade** [comment]
Great of you to point this out @tommy-carlier. 👍 

To the authors: please also note the [media type registration procedures][1] which states that media types in the [standards tree][2] *must* be either:

> 1.  in the case of registrations associated with IETF specifications, approved directly by the IESG, or
> 2.  registered by a recognized standards-related organization using the "Specification Required" IANA registration policy [RFC5226] (which implies Expert Review). 

[1]: https://tools.ietf.org/html/rfc6838
[2]: https://tools.ietf.org/html/rfc6838#section-3.1
[RFC5226]: https://tools.ietf.org/html/rfc5226

**Comment by vitorgalvao** [comment]
For consideration by the authors, the (current) top comment on HN has a lengthy discussion on the merits (or lack thereof) of this change. Most seem to concur the change should happen.

**Comment by ttepasse** [comment]
The W3C and WHAT WG versions of HTML [overloaded](https://www.w3.org/TR/html5/links.html#rel-alternate) `rel=alternate` just for the media types `application/rss+xml` and `application/atom+xml`. If one of these is not there it means alternative representation of the current document, not "there is a feed for this blog". If a new media type get's registered, someone should also petition WHATWG and W3C for its inclusion in the HTML specs.

(There was a proposal of `rel=feed` somewhere. That proposal seems dead except for some usage for the HTML feeds of the Indieweb movement. Maybe that's easier)

**Comment by danielcompton** [comment]
Relates to #7.

**Comment by aaronpk** [comment]
fwiw I just hit this problem trying to build in feed discovery into my reader. Because right now I have to look for `application/json`, my feed discovery is returning other URLs like peoples' oembed endpoints when looking for the jsonfeed, and then those URLs obviously fail to be subscribed to.

**Comment by manton** [comment]
Keeping #32 open for this. Thanks!
