### ISSUE TITLE
Is there any plan for writing a XML to JSON feed converter.

### ISSUE THREAD

**Issue by knoxxs** [brentsimmons/JSONFeed#25]
This can help people start converting feed in json. They don't have to wait till everyone supports json feed.

**Comment by manton** [comment]
I wrote a quick Ruby script, mostly to experiment with converting RSS podcast feeds. It's not perfect but may help get you started. https://gist.github.com/manton/03a41efd6ebb1afa4ff3c482b83d1097

**Comment by manton** [comment]
There's also a separate converter on the web now: https://feed2json.now.sh. Hopefully one of these helps, so I'm going to close this. Thanks!
