### ISSUE TITLE
Basic Question about JSON Feed Format?

### ISSUE THREAD

**Issue by collegeitdept** [brentsimmons/JSONFeed#29]
Sorry for the basic question about the JSON Feed Format:

Will this also help with the implementation of the Apple News Format (since it's also JSON)?

Thanks

**Comment by vallieres** [comment]
Unrelated. Both are different specs and JSONFeed is aimed to be a modern twist on the old XML feed (news, blogs, websites, etc). Apple News Format is another JSON based spec with the sole purpose to be parsed by the Apple News app.
