### ISSUE TITLE
№ of subscribers in User-Agent header fragments caches

### ISSUE THREAD

**Issue by tigt** [brentsimmons/JSONFeed#3]
I suspect the `(n subscribers)` substring in `User-Agent` is from existing reader behavior, but it means edge caches that `Vary` on UA accumulate a dead copy every time a feed gets a new subscriber. (UA-sniffing is inadvisable, but widespread.)

Not a huge issue, but I’m curious what the authors think.

**Comment by manton** [comment]
Interesting point about edge caches, thanks. You're right, this is just a convention that many existing feed readers and podcast clients use. Seemed a nice suggestion to include in the spec. (A separate HTTP header is probably a better place for this info, but I'm not aware of any readers that do that, and it's probably outside the scope of JSON Feed to split with current practice.)

**Comment by da2x** [comment]
Please preserve the User-Agent the way it is. It’s useful.

`Vary: User-Agent` will fragment caches in a million ways anyway. If you really want to use `Vary: User-Agent` then you should also use the [Key](https://tools.ietf.org/html/draft-ietf-httpbis-key-01) header (e.g. `Key: User-Agent; substr="mobile; substr="JSONFeed"`) mechanism and a compatible caching server to avoid unnecessary fragmentation.

**Comment by manton** [comment]
Thanks. I think an argument could be made to leave this out of the spec, but it's part of the section with general tips for building feed readers and not something that most people will need to read, so I think it's fine.
