### ISSUE TITLE
Valid values for `version`

### ISSUE THREAD

**Issue by sonicdoe** [brentsimmons/JSONFeed#31]
I have noticed that https://manton.org/feed/json specifies the version `http://jsonfeed.org/version/1` instead of `https://jsonfeed.org/version/1` (`http` vs. `https`). Is this considered a valid version?

**Comment by gruber** [comment]
It should be https, and I think jsonfeed.org should redirect all http calls to https.

**Comment by manton** [comment]
Thanks for noticing @sonicdoe! I've just fixed this in the WordPress plugin and updated my site. And I agree with @gruber that we might as well start redirecting to https now.

**Comment by valtlai** [comment]
Should parsers support both or https only?

**Comment by gruber** [comment]
I say follow Postel's Law: https://en.wikipedia.org/wiki/Robustness_principle

A parser shouldn't fail over this, but a validator should issue a warning suggestion over it.

**Comment by sonicdoe** [comment]
Thank you for clarifying. I’ve taken the liberty of closing this issue.
