### ISSUE TITLE
Allow items to be an map object

### ISSUE THREAD

**Issue by Alazoral** [brentsimmons/JSONFeed#37]
Several JSON-focused technologies, including Firebase, natively serialises collections of entities as objects which are keyed with their contained entity's id.

My proposal would be to allow this behaviour, optionally, for the items field. This would allow many applications to export JSON feeds almost automatically, by merely wrapping or just being moderately careful about their data schema.

Thanks for your all your hard work, JSON Feed is great.

**Comment by manton** [comment]
Thanks! Just to be clear I understand, you mean something like this?

```items: {
  "123": {
    "id": "123",
    "content_text": "Hello"
  }
  ...
}```

**Comment by manton** [comment]
In general there shouldn't be 2 ways to do the same thing, nor a single field that can have multiple representations (array vs. dictionary). We've had a few debates related to this on other fields, and it's always best to go with the most clear option.

**Comment by Alazoral** [comment]
Yes, that syntax, perhaps even omitting the id field.

I can certainly appreciate that having two formats would harm the simplicity of it for client implementors. Is there a particular reason an array was chosen for the items field type?

**Comment by theckman** [comment]
@Alazoral One reason I can think of is that an Array type guarantees order, while an Object type does not. You could rely on the Items field to be the items in chronological order. Parsers of JSON objects aren't always able to guarantee that keys will be presented to the programer in the same order they were parsed. In other words, looping over the keys in a map may not be in the same order as the original JSON document.

The authors hint to this in the explanation of the `version` field:
>This should appear at the very top, though we recognize that not all JSON generators allow for ordering.

**Comment by manton** [comment]
For simplicity I like keeping this as an array. Thanks for the feedback.
