### ISSUE TITLE
Are URLs URLs?

### ISSUE THREAD

**Issue by ttepasse** [brentsimmons/JSONFeed#39]
The spec mentions the data type URL which is a string in JSON terms. I'm wondering about the syntactic requirement of these strings. Are these URL normalized URIs per [RFC 3986](https://tools.ietf.org/html/rfc3986)? Or are they IRIs per [RFC 3987](https://tools.ietf.org/html/rfc3987)? Or are they „URLs“ per the WHATWGs [URL spec](https://url.spec.whatwg.org)?

**Comment by skyzyx** [comment]
Excellent question, for those of us who are implementing.

**Comment by manton** [comment]
Closing this since I don't think the JSON Feed spec needs to point to one of these other URL RFCs. Thanks!

**Comment by ttepasse** [comment]
That didn't answer the question.
