### ISSUE TITLE
Language & Internationalization

### ISSUE THREAD

**Issue by ttepasse** [brentsimmons/JSONFeed#40]
People outside the United States speak other languages. Sometimes they even write in another script. It happens.

One thing JSON feeds lose without the XML ecosystem is XML's great support for i18n. When processing an JSON feed for end users, language information is somewhat important: for assistive technologies (e.g. pronounciation), for display (directionality of text, other advanced layout), maybe just for filtering multilingual feeds.

`item.content_html` in theory could carry its own `html:lang` or `xml:lang` attribute. But `title`, `description`, `item.title`, `item.content_text`, `item.summary`, `item.attachment.title` and maybe `item.tags[]` don't have language labeling.

Proposal: 
- a new key named `language` (optional, string) which contains a [BCP 47](https://tools.ietf.org/rfc/bcp/bcp47.txt) language tag. 
- the key should be used top-level, item-level, maybe attachment-level and maybe in extensions. Which would put a new, small limit on extensions.
- Like for `xml:lang` and `html:lang` child elements should inherit their parents language definition unless they define their own.
- I would make top-level `language` required, because I can't think of an feed example which doesn't have some form of human language somewhere. Even commits or server logs or other technical stuff often has language in it.

Also: I never got into the details of the Bidi algorithm. But `html:dir` and `xml:dir` exist and seem to fill a need which sometimes seem to be reasonable.

**Comment by voxpelli** [comment]
👍 And as I mentioned in #41, `hreflang` for links would also be interesting in regards to this.

In a multi-lingual world where feeds are not just long articles, but also short micro-blog notes, it could also be interesting to support multiple languages within the content itself, so that one could write the same feed item in both Swedish and English at once. This is something we've discussed in the Microformats world: https://github.com/microformats/microformats2-parsing/issues/3 As this format and the [JSON-representation (JF2)](http://microformats.org/wiki/jf2) of Microformats 2 is very similar, one could take some inspiration from there and maybe even work towards closing the gap between the two.

**Comment by NorbertLindenberg** [comment]
Not sure why this bug description says "outside the United States". According to the latest (2015) data from the US Census Bureau, over 62 million US residents of age 5 and over, 21% of the total, speak a language other than English at home.
https://factfinder.census.gov/faces/tableservices/jsf/pages/productview.xhtml?pid=ACS_15_5YR_DP02&src=pt

**Comment by fboes** [comment]
Until an official standard drops, I do this at root and `items`-level:

```json
"_language": {
  "about": "https://github.com/brentsimmons/JSONFeed/issues/40",
  "language": "en"
}
```

Hopefully, someday this will be like:

```json
"language": "en"
```

**Comment by seiz** [comment]
+1 for this. 

RSS had this for the top level <channel>, so i suggest to also add this as optional to the top level as well as on the item level. If only given at the top level and omitted at the item level, items should inherit the language from the top level.

Example:

	{
		"version": "https://jsonfeed.org/version/1",
		"language": "de",
		"title": "My Example Feed",
		"home_page_url": "https://example.org/",
		"feed_url": "https://example.org/feed.json",
		"items": [
			{
				"id": "2",
				"content_text": "This is a second item.",
				"url": "https://example.org/second-item"
			},
			{
				"id": "1",
				"content_html": "<p>Hello, world!</p>",
				"url": "https://example.org/initial-post",
				"language": "en",
			}
		]
	}

**Comment by ttepasse** [comment]
Rereading a year later: My proposal has of course a deficit: What happens when for example `item.title` is in french and `item.text_content` in english? What should item.language be?

XML of course solves this by allowing `xml:lang` on every element.
JSON-LD solves this in multiple ways, the easiest seem to be value objects, resulting in language-tagges strings.

**Comment by manton** [comment]
Thanks y'all. I'm going to close this because I think there has been more discussion in #62.
