### ISSUE TITLE
Clarify WebSub support

### ISSUE THREAD

**Issue by voxpelli** [brentsimmons/JSONFeed#46]
As discussed on Twitter ([see thread](https://twitter.com/julien51/status/865232127184338945)) the current `hubs` property in JSON Feed is not supported by the discovery mechanisms provided by [WebSub](https://github.com/w3c/websub) (formerly known as PubSubHubbub).

This partly ties into #44 as WebSub currently [only supports](https://w3c.github.io/websub/#discovery) discovery through the Link Relations standardized in the [RFC 5988](https://tools.ietf.org/html/rfc5988) that is mentioned in #44. (And currently also through `hostmeta`, but that support is [at risk](https://github.com/w3c/websub/issues/97))

Of the standard ways outlined in RFC 5988, only the HTTP `Link:` header one can be applied to JSON Feed. There is no standardized way to include link relations within JSON as there is within XML and HTML.

So unless WebSub is extended to specifically support a JSON Feed specific discovery mechanism, then the only supported discovery mechanism is the HTTP `Link:` header.

Ping @manton @julien51

**Comment by manton** [comment]
Thanks @voxpelli. I've also filed an issue on WebSub to relax the wording of how hubs are discovered: https://github.com/w3c/websub/issues/107. Importantly, that change is small and wouldn't rule out extending WebSub to know about JSON documents in the future, which is a larger discussion.

**Comment by julien51** [comment]
> There is no standardized way to include link relations within JSON as there is within XML and HTML.

I think this is the view issue here. As much as I wish we should just add a discovery mechanism surgically for jsonfeed, what happens when socialfeed is stated? Etc...

**Comment by voxpelli** [comment]
Considering that https://github.com/w3c/websub/issues/107 is now closed with no changes made to that spec, should the conclusion be that JSON Feed won't be WebSub compatible but rather just WebSub inspired?

Because either JSON Feed or WebSub has to change for the two to be compliant as the current wording of the two are not.

Sorry for being pushy about this, it's just that it would be great if we could ensure that the standards that emerge on the independent web stay as compatible and as compliant as possible when it comes to shared mechanisms 😕

**Comment by scripting** [comment]
What is WebSub?

**Comment by aaronpk** [comment]
What I would really like to see is a generic link rel discovery method for JSON formats in general. This would be something JSONFeed could adopt, and also something that WebSub could recommend as the discovery format for JSON documents. At least this way other JSON formats would have a standard to point to as well.

The Microformats 2 JSON format has been around for quite a long time and fits this bill. Basically it defines a dictionary as a top-level property of the JSON document that looks like this:

```json
{
  ...your other json here...
  "rels": {
    "stylesheet": [
      "/styles.css"
    ],
    "hub": [
      "https://switchboard.p3k.io/"
    ]
  }
```

Any HTML link rels in the document are added to that part of the JSON document during parsing. This would certainly work as a generic JSON link rel format and could be written up as its own spec that JSONFeed and WebSub could support.

**Comment by voxpelli** [comment]
@scripting WebSub is what was formerly known as Pubsubhubbub – so it's the format independent mechanism for delivering content in realtime

**Comment by scripting** [comment]
Aha! Then it's an interesting argument because PSHB didn't have much regard
for prior art when they entered the web syndication world. ;-)

The truth is that people who invent specs do it not so much for interop,
because if that were the goal they'd do it differently.

The JSON Feed project and what's now called WebSub have that in common.

Dave

**Comment by manton** [comment]
I think we can close this. There was a good discussion in the WebSub repository: https://github.com/w3c/websub/issues/107
