### ISSUE TITLE
JSON Feed Validator Plans

### ISSUE THREAD

**Issue by benubois** [brentsimmons/JSONFeed#50]
Hi,

JSON Feed looks great!

I was wondering if there were any plans for an official validator tool/web service? I think this would be very useful to help people get their feeds right. 

In addition to checking that a feed is valid JSON, it could also check:

- Proper content-type headers
- Presence of required fields
- Valid URLs for the feed
- Make recommendations (like fully qualified URLs in #8)

Thanks!

**Comment by voidfiles** [comment]
I had the same idea. ;)

So, I made one https://github.com/voidfiles/jsonfeedvalidator

**Comment by dce** [comment]
I put something simple up here: https://json-feed-validator.herokuapp.com/

But then I noticed this on the official Twitter account: https://validator.jsonfeed.org/

**Comment by ndarville** [comment]
I for one support some competition in this area. :)

**Comment by manton** [comment]
Thanks y'all. Glad these JSON Feed validators exist. Going to close this issue.
