### ISSUE TITLE
Non-object extensions

### ISSUE THREAD

**Issue by sonicdoe** [brentsimmons/JSONFeed#59]
As far as I understand, extensions have to be an object:

> Publishers can use custom objects in JSON Feeds. Names must start with an `_` character and be followed by a letter. Custom objects can appear anywhere in a feed.

However, @manton [just wrote](https://github.com/brentsimmons/JSONFeed/issues/19#issuecomment-302918757) in another issue:

> … let's imagine that`sticker` in one extension is a string value (maybe a URL), and in another extension is an object (maybe with type, size, and URL).

Do extensions have to be an object or are non-object extensions also valid?

**Comment by manton** [comment]
They have to be objects. Sorry about the confusion. In trying to come up with hypothetical examples I went too far inventing an extension. :-) I'll update that other issue.
