### ISSUE TITLE
Version number is unnecessary

### ISSUE THREAD

**Issue by hsivonen** [brentsimmons/JSONFeed#68]
> A version 1 feed will be a valid version 2 feed, and so on. Future versions may add things, but won’t make older feeds invalid.

What about future feeds in older readers? The spec doesn't contain a detailed processing model, but chances are that the reasonable behavior when encountering the lack of version or a version from the future is to simply ignore the version.

If that's the case (I hope it is), it would make the most sense not to declare a version at all. E.g. CSS never did and HTML no longer does. Please consider dropping the top-level `version` key.

**Comment by manton** [comment]
Even if feed readers ignore `version`, it's useful for anyone looking at the feed and wondering what it is, since it links to the documentation.

**Comment by valtlai** [comment]
Could we use something like

```json
"format": "https://jsonfeed.org"
```

instead?

**Comment by hsivonen** [comment]
If you find a feed-looking thing in JSON, a Google search for "JSON feed" finds the JSONFeed spec.

If baking the spec URL into each feed is still considered useful (I don't think it is useful enough since a Google search works), I think it would be good to make it clear that such a URL is not required in the format and does not participate in processing in any way.

**Comment by callionica** [comment]
At some point it is likely that feed readers will need to sniff the content to determine what it is (this is made more likely by not having a jsonfeed-specific MIME type, not having a jsonfeed-specific file extension, and not having a clearly specified discoverability mechanism from HTML). Given this, it is worth designing the format to be efficiently sniffable, which means including a unique identifier early in the document. The version currently serves this purpose.

**Comment by dret** [comment]
https://twitter.com/fielding/status/376835835670167552

**Comment by manton** [comment]
I think we're good keeping the version URL as it is. Thanks y'all.
