### ISSUE TITLE
Extensiblity model

### ISSUE THREAD

**Issue by dret** [brentsimmons/JSONFeed#88]
one of atom's success stories was a diverse and evolving ecosystem of shared extensions. http://dret.typepad.com/dretblog/atom-landscape.html is where i tried to keep track of that landscape back in the atom days.
for JSON feed, extensions currently seem to be an entirely private thing (using the `_` prefix). is there any plan or need to be able to have extensions that have shared meaning? it's arguably harder to define easily in JSON because of the lack of naming and namespaces. but it still would be possible to allow new member names and make their names discoverable through a registry, for example.

**Comment by manton** [comment]
I think it's a good idea to collect a list of extensions, so that someone thinking up a new extension can see if anyone has already tackled the problem. I'm not sure where that page should live, or whether it should be manually curated or user-submitted, but something like that would certainly be useful.

**Comment by dret** [comment]
On 2017-05-30 21:15, Manton Reece wrote:
> I think it's a good idea to collect a list of extensions, so that
> someone thinking up a new extension can see if anyone has already
> tackled the problem. I'm not sure where that page should live, or
> whether it should be manually curated or user-submitted, but something
> like that would certainly be useful.

there are many different ways to approach this, 
https://tools.ietf.org/html/draft-wilde-registries is something i wrote 
up recently to serve as guidance for these kinds of scenarios.

two examples come to mind how these registered/well-known extensions 
could be managed (and the question then is whether these should use the 
underscore extension syntax, or would be allowed to use non-prefixed names):

- IETF/IANA have managed registries that are based on review and a 
controlled publication process. these have worked exceptionally well for 
the internet, but for web-level things there sometimes is a dispute 
whether this approach isn't a bit too arcane and opaque.

- i have a pet project where i try to come up with a more open and 
transparent approach, where registry submissions and the registry are on 
github, and thus collaboration and control can use regular github 
processes. the idea is to remove the "expert review" and gatekeeper for 
the registry that some people dislike about the IETF/IANA model.

**Comment by dret** [comment]
regardless of the way extensions are made discoverable (as suggested in https://github.com/brentsimmons/JSONFeed/issues/94 as a separate issue), it also would be good to have a hard look at the current extensibility model. https://github.com/brentsimmons/JSONFeed/issues/100 points out one specific problem and is a good indication that maybe a different approach would work better:
* do not separate namespaces into blessed and private (https://tools.ietf.org/html/rfc6648)
* do have a clear extension and processing model (http://dret.typepad.com/dretblog/2016/04/robust-extensibility.html)
* do have a way of how extensions are made discoverable and thus shareable (https://tools.ietf.org/html/draft-wilde-registries)

**Comment by manton** [comment]
Thanks again. Going to close this since there's not currently a central place to list extensions. If one pops up, we can link to it.
