### ISSUE TITLE
Event Calendar Items

### ISSUE THREAD

**Issue by davidfindlay** [brentsimmons/JSONFeed#91]
One thing I see lacking in RSS is the ability to have items that advise about future events. For instance, I want to syndicate the Swimming Meet Event calendar for my sporting organisation, so that individual clubs could include the calendar of upcoming events on their site.

With RSS I could do so by putting the upcoming date in the title of the item. However I'd like to be more semantic about it.

I'd suggest just adding a 'eventdate' optional field to item. This would then allow implementations to feature future events.

**Comment by scripting** [comment]
If I were going to build an app like that I might not use RSS, because I tend to think of it for publishing applications. That said, you could use the pubDate sub-element of item in RSS to carry the date. Or you could use a namespace. There might be an RSS namespace for calendar type events. Worth a look before reinventing imho. ;-)

**Comment by davidfindlay** [comment]
Well that is the intention, as it's so I can publish things from our national body to be featured on our club sites. RSS was my initial thought due to it's ubiquity and compatibility. I'd rather use an established protocol.

I just figure that in a new refiguring of the feed as in JSONFeed it'd be a useful use case to cover.

**Comment by BenLeggiero** [comment]
I love this idea! I would love to see and make teasers and such to hype up the next item. 
I imagine a podcast queueing up the next month of episodes, or an internet videographer for their next production, or a blog its next big post... And readers could allow users to watch these for when they go live! Oh I love this idea so much.

**Comment by manton** [comment]
Thanks! There's some great examples here. I think it should probably be implemented as a JSON Feed extension, so I'm going to close this… If someone works on it and wants to encourage other people to support the extension, feel free to post a comment here.
