### ISSUE TITLE
Support for multiple authors.

### ISSUE THREAD

**Issue by markdorison** [brentsimmons/JSONFeed#97]
While implementing v1 of the spec, it occurred to me that it would be valuable to be able to specify multiple authors on content items. Would you consider this in scope for a future version?

**Comment by Hatlen** [comment]
👍 and probably also on the root level author/authors object/array.

**Comment by Hatlen** [comment]
Saw this issue https://github.com/brentsimmons/JSONFeed/issues/6  now about the same thing

**Comment by markdorison** [comment]
Yes, this is a dupe of #6. Closing.
